### ISSUE TITLE
new home and licence change

### ISSUE THREAD

**Issue by konstantinstadler** [IndEcol/country_converter#128]
I plan some restructuring of the country converter coco in early 2023.

1) I will move the coco repository to a new home at https://github.com/IndEcol . This is an effort to emphasis the community aspect of coco - I want to avoid the impression that this is just "my" project (but of course I will continue developing it).
2) I plan to change the licence to LGPL3. This is a more permissive licence than the current GPL3. The main reason is that I want to make it easier for people to use coco in their own projects and not enforce a GPL licence for their projects. At the same time I still want to ensure that any modifications on coco stay open. My understanding is that LGPL3 achieves that - but I am not expert and would appreciate feedback on that. 

This is open for anyone to discuss/provide feedback here, in particular for former contributors (@sbrugman @mcarans @alanorth @jm-rivera @Kajwan @jpatokal @rgieseke @MohamedhBadr @CandyDeck @Alex-Mackie @rlonka @WillMoggridge @vincentarelbundock )

The plan is to do these changes by End of January 2023. I will do a final reminder one week before the change.

**Comment by vincentarelbundock** [comment]
Thanks for tagging me. I don't know `country_converter`, so I'm not sure if this is relevant, but is any of the code (such as the regexes) based on the `countrycode` package for `R`? If so, you should note that that code is GPL. See: 

https://cran.r-project.org/web/packages/countrycode/index.html

IANAL, but my understanding is that you can sublicense LGPL code under GPL, but not the other way around.

**Comment by konstantinstadler** [comment]
Good point, thanks for the feedback @vincentarelbundock . Indeed, the first draft of regexes came from this package. There have some several changes since then, but I guess one can still see the underlying original.

So this probably sets the license for coco. Just out of curiosity - why did you settle for GPL and not for LGPL? Reason I am asking - I now had several projects asking for changing to a more permissive licence since the "soft linking" of the licence is not well-defined for the python architecture.

**Comment by vincentarelbundock** [comment]
I don't want to pretend there was deep thinking behind the decision. Nearly all the R packages on CRAN are GPL, so it felt natural. Philosophically I am not an extremist, but I still like being a bit more aggressive about promoting open source.

Finally, wrangling all the people who contributed to the package since 2009 to get their views on re-license seems like more trouble than it's worth to me.

**Comment by alanorth** [comment]
Thanks for the heads up @konstantinstadler. I have only made a few minor contributions here and I'm OK with both GPL and LGPL, though I'm not a lawyer so I'm not sure about relicensing. For what it's worth, I do license all my projects as GPL where possible so that code from the community stays in the open.

**Comment by konstantinstadler** [comment]
Ok, so based on this we will keep the GPL licence. So the remaining point is the move to the IndEcol group.

**Comment by jm-rivera** [comment]
Yes thanks for the heads up @konstantinstadler. Makes sense on the license.

As for moving it to the IndEcol group, also seems sensible. Hopefully this won't change the contribution dynamics too much.
We use the package quite a bit, so I'm always happy to contribute to it. 

Are you planning further development as part of the move? It would be great to get a sense of your roadmap to see where I could contribute (if helpful).

**Comment by konstantinstadler** [comment]
I do not plan to change the dynamic at any way from my side. 
However, I would be very happy for others also helping managing the package / being co-owners.

Regarding the roadmap:
For my current needs the package has all functionality it needs. 
So I might update the underlying data file (new classifications, bug-fixes, update names) but don't have any immediate plans to extend the functionality. However, as long as it is does not break any existing functionality there is no problem to include extensions.

**Comment by konstantinstadler** [comment]
done in version 1.0.0 - thanks for all the feedback!
